package exercise05.pkg7;

import javax.swing.JOptionPane;

/**
 * Form to allow users to Add or Edit a StockItem in a StockItemCollection
 *
 * @author Mary Cronin 0510661
 */
public class FrmStockItemEdit extends javax.swing.JInternalFrame {

    private int stockItemId;
    StockItemCollection stockItemCollection;
    StockItem editStockItem;

    /**
     * Creates new form FrmStockItemEdit
     *
     * @param stockItemId - Unique identifier for a stock Item
     */
    public FrmStockItemEdit(int stockItemId) {
        initComponents();

        try {
            stockItemCollection = new StockItemCollection();
        } catch (ApplicationException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Problem", JOptionPane.ERROR_MESSAGE);
        }

        // Store the location id
        this.stockItemId = stockItemId;

        // Decide on Add or Edit form presentation, 0 is add
        if (stockItemId == 0) {
            this.title = "Add new Stock Item";
            try {
                editStockItem = new StockItem(0, 0, " ", " ", 0.0);
            } catch (ApplicationException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Problem", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            this.title = "Edit Stock Item  Id: " + stockItemId;
            while (stockItemCollection.moveToNextStockItem()) {
                if (stockItemCollection.getCurrentStockItem().getStockItemId() == stockItemId) {
                    editStockItem = stockItemCollection.getCurrentStockItem();
                }

            }

        }
        PopulateFormFields();
    }

    /**
     * Method to populate stockItem with entries made into form
     */
    private void PopulateFormFields() {
        this.txtPartNumber.setText(Integer.toString(editStockItem.getPartNumber()));
        this.txtStockName.setText(editStockItem.getName());
        this.txtDescription.setText(editStockItem.getDescription());
        this.txtUnitPrice.setText(Double.toString(editStockItem.getUnitPrice()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPartNumber = new javax.swing.JTextField();

        jLabel1.setText("Stock Name");

        txtStockName.setText("jTextField1");
        txtStockName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStockName.setMinimumSize(new java.awt.Dimension(150, 25));
        txtStockName.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel2.setText("Description");

        txtDescription.setText("jTextField2");
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDescription.setMinimumSize(new java.awt.Dimension(150, 25));
        txtDescription.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel3.setText("Unit Price $");

        txtUnitPrice.setText("jTextField3");
        txtUnitPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUnitPrice.setMinimumSize(new java.awt.Dimension(100, 25));
        txtUnitPrice.setPreferredSize(new java.awt.Dimension(100, 25));

        BtnSave.setBackground(new java.awt.Color(153, 255, 153));
        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Part Number");

        txtPartNumber.setText("jTextField1");
        txtPartNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPartNumber.setMinimumSize(new java.awt.Dimension(150, 25));
        txtPartNumber.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStockName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPartNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(BtnSave)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to Save stock item entered in form
     *
     * @param evt - Event Action
     */
    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        try {
            int partNumber = Integer.parseInt(this.txtPartNumber.getText());
            String stockName = this.txtStockName.getText();
            String description = this.txtDescription.getText();
            double unitPrice = Double.parseDouble(this.txtUnitPrice.getText());

            editStockItem.setPartNumber(partNumber);
            editStockItem.setName(stockName);
            editStockItem.setDescription(description);
            editStockItem.setUnitPrice(unitPrice);
            // If adding a new entry, put it into the collection
            if (stockItemId == 0) {
                editStockItem.setStockItemId(stockItemCollection.getNextID());
                stockItemCollection.addStockItem(editStockItem);
            }
            stockItemCollection.saveStockItem(stockItemId);
            JOptionPane.showMessageDialog(null, "Change Saved", "Sucess", JOptionPane.INFORMATION_MESSAGE);
            if (stockItemId > 0) {
                // return to the Inventory Find screen
                FrmMain frmMain = (FrmMain) this.getTopLevelAncestor();
                frmMain.FindStockItem();
                this.dispose();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid entry: " + ex.getMessage(), "Problem", JOptionPane.ERROR_MESSAGE);
        } catch (ApplicationException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Problem", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BtnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPartNumber;
    private javax.swing.JTextField txtStockName;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
